### ISSUE TITLE
Status Board app is no longer for sale

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/edd-status-board#17]
I did some digging and discovered that although the app should still work if you already own it, [Panic has discontinued development of Status Board](https://panic.com/blog/the-future-of-status-board/) and is no longer selling it. Noting here as there are some bugs which need to be fixed, but if we release an update to this plugin, we need to update the readme, etc. to indicate that the extension can only be used if you already own the app.

Also should we consider deprecating/sunsetting this extension? Since the app it connects to is no longer available?

**Comment by ashleyfae** [comment]
> Also should we consider deprecating/sunsetting this extension?

IMO yes.

**Comment by pippinsplugins** [comment]
I agree, discontinue.
